-- SQL Insert Script para video_sources
-- Generado automáticamente por Vivotv Helper (Refactored)

INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1234811, 'https://vimeos.net/embed-d8sk7n8weboz.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Nuestro Secretito (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1234731, 'https://vimeos.net/embed-8ui84v2hjx3j.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Anaconda (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1625430, 'https://vimeos.net/embed-0v9tmic7h2z0.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Código negro (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1233413, 'https://vimeos.net/embed-w4ye5qur4pxz.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Pecadores (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1233243, 'https://vimeos.net/embed-7nwexrp73opo.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Last Redemption (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1233199, 'https://vimeos.net/embed-8shp2tn53zzy.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Crónicas de Exorcismo: El Comienzo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1233069, 'https://vimeos.net/embed-qm08bcgkqxdf.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Extraterritorial (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1232943, 'https://vimeos.net/embed-nz2tkojj8mxm.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Mátame si te atreves, cariño (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1232933, 'https://vimeos.net/embed-humc4ypgwkkb.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Terror en el rio (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1232546, 'https://vimeos.net/embed-05cj58qowmxd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Until Dawn: Noche de terror (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1231953, 'https://vimeos.net/embed-asnbzgczelnt.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Cinco Citas a Ciegas (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1231574, 'https://vimeos.net/embed-ptj60knm77op.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Mi querida oni (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1231155, 'https://vimeos.net/embed-brd4cgxu3bsr.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Never Have I Ever (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1230550, 'https://vimeos.net/embed-io87fu48ji17.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Sen Büyümeye Bak (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1230393, 'https://vimeos.net/embed-67h0oxem32c5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Monsters: El infierno del dragón (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1230368, 'https://vimeos.net/embed-b12dd5m2fbbg.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Springsteen: Música de ninguna parte (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1230208, 'https://vimeos.net/embed-pfl2pqqjdc6e.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Bastión 36 (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1230085, 'https://vimeos.net/embed-6bugxu6ge1dv.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Ceniza (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1229958, 'https://vimeos.net/embed-iketmbd7htlr.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Lover, Stalker, Killer (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1229945, 'https://vimeos.net/embed-ulfsaryik5gd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Tricks Can Go Wrong (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1229913, 'https://vimeos.net/embed-2qlntrbf53uu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El Roomie (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1229586, 'https://vimeos.net/embed-cjxkj7886q94.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Stutter (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1229461, 'https://vimeos.net/embed-t8t16eaqune8.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Behold, A Pale House (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1468860, 'https://vimeos.net/embed-igs9y4sufy8t.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Audrey (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1229262, 'https://vimeos.net/embed-3c6x0n566xzq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- I Don't Understand You (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1228246, 'https://vimeos.net/embed-coi7n8m5bafw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Five Nights at Freddy's 2 (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1227852, 'https://vimeos.net/embed-3p1zfw9jyflc.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Las Tres Sisters (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1227816, 'https://vimeos.net/embed-bbdhbgqk1mv3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Pacto de sangre (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1227433, 'https://vimeos.net/embed-mcyp77iyg3n2.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Him (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1226841, 'https://vimeos.net/embed-o9b6j4us1qzm.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La gran noche del pop (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1226840, 'https://vimeos.net/embed-9m02yrlwgu41.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Things Will Be Different (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1226578, 'https://vimeos.net/embed-i2cib8zu0itu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Longlegs: Coleccionista de almas (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1226406, 'https://vimeos.net/embed-j9h6s0zi4eew.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Amor explosivo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1225915, 'https://vimeos.net/embed-y63ld1wtv01s.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El ladrón de joyas (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1225582, 'https://vimeos.net/embed-iahiqsw6bla7.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Inside (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1225572, 'https://vimeos.net/embed-glrwlnnuo2ls.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Screamboat La Masacre Del Ratón (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1223601, 'https://vimeos.net/embed-d2dfb6adxhmu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Sisu: Camino a la venganza (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1221388, 'https://vimeos.net/embed-ws91f7vz0d4e.html') ON CONFLICT (tmdb_id) DO NOTHING; -- De las cenizas (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1221118, 'https://vimeos.net/embed-f7gozvybg7iu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Perder es ganar un poco (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1219926, 'https://vimeos.net/embed-3mgva5eel7bc.html') ON CONFLICT (tmdb_id) DO NOTHING; -- South Park (No Apto Para Menores) (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1219735, 'https://vimeos.net/embed-0byr66ivdfky.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una Película de Amor y Guerra (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1219559, 'https://vimeos.net/embed-hsf0ictz5oj5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Por Siempre RBD (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1219548, 'https://vimeos.net/embed-a5eafqpxxabl.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Der Medicus II (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1219491, 'https://vimeos.net/embed-h8pdcpkox4sd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una Navidad para Chueco (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1218925, 'https://vimeos.net/embed-gbjdqxg2thzt.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Chainsaw Man – La película: Arco de Reze (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1218762, 'https://vimeos.net/embed-27p1zzn64848.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Un robo muy navideño (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1217690, 'https://vimeos.net/embed-fehfhamckj8w.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Homestead (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1217602, 'https://vimeos.net/embed-qhuj6scpxlub.html') ON CONFLICT (tmdb_id) DO NOTHING; -- London Calling (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1217409, 'https://vimeos.net/embed-9tijcmyc33sl.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Jaque Mate (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1216780, 'https://vimeos.net/embed-pn6054f6trw0.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Tonterías de amor (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1216611, 'https://vimeos.net/embed-s9ha451xiuh3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- TikTok: In the Mix (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1216299, 'https://vimeos.net/embed-2k2la57zmhov.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La Noche que Volvimos a Casa (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1216268, 'https://vimeos.net/embed-rwurr06fugpn.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La agencia del desamor (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1215918, 'https://vimeos.net/embed-dg8a8kunprh3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Blackwater Lane (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1215798, 'https://vimeos.net/embed-63kwf14wflrj.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Cut (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1215077, 'https://vimeos.net/embed-ie667z3mhwix.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Gazer (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1215020, 'https://vimeos.net/embed-2r1sd11sxtty.html') ON CONFLICT (tmdb_id) DO NOTHING; -- American Sweatshop (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1214891, 'https://vimeos.net/embed-9pwufmfkbutq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Huida sangrienta (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1214684, 'https://vimeos.net/embed-63oclc3bepmf.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El beso de la mujer araña (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1214509, 'https://vimeos.net/embed-f08c96191clq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Asesino Por Naturaleza (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1214508, 'https://vimeos.net/embed-wtrjc5nab4fn.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Hijo de sicario (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1214484, 'https://vimeos.net/embed-77aiyk6l5ioj.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Aprender a soltar (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (808396, 'https://vimeos.net/embed-jfr7xg7zwj3v.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Otra bala más (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1214130, 'https://vimeos.net/embed-vlhg0iwe557u.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Frankie y Los Monstruos (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1213997, 'https://vimeos.net/embed-u1x49jw2kynl.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Criptoestafas (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1213742, 'https://vimeos.net/embed-jimjqofs9e57.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Divorcio en negro, de Tyler Perry (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1212855, 'https://vimeos.net/embed-3p2h1frxn7su.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Fight or Flight (Sicarios en el aire) (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1212742, 'https://vimeos.net/embed-n65w8z2u3vey.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Rule of Jenny Pen (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1212461, 'https://vimeos.net/embed-y2wp7od85g7y.html') ON CONFLICT (tmdb_id) DO NOTHING; -- OBEX (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1212325, 'https://vimeos.net/embed-r7tcm755hc9d.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Assemblage (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1212142, 'https://vimeos.net/embed-429bjjq7fjp2.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Algo embarazada (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1212073, 'https://vimeos.net/embed-te4hv9isodmx.html') ON CONFLICT (tmdb_id) DO NOTHING; -- 60 minutos (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1211419, 'https://vimeos.net/embed-59cjhp4fpol4.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Mi cuñado es un vampiro (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1211199, 'https://vimeos.net/embed-hq9jlsoufrxf.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Gracias, lo siento (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1211066, 'https://vimeos.net/embed-2uc5ickq1z7n.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La Fierecilla Indomable 2 (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1467482, 'https://vimeos.net/embed-md2oz8dczdsg.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Revelación (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1210732, 'https://vimeos.net/embed-8mnkj3zhxd66.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Misterioso asesinato en la montaña (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1210089, 'https://vimeos.net/embed-vpwmqj014hgd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- C.I.C. - Central de Inteligência Cearense (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1209290, 'https://vimeos.net/embed-bz0bgwew6h8y.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Liga de la Justicia: Crisis en Tierras Infinitas – Parte 3 (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1209288, 'https://vimeos.net/embed-2y6an4p7v39m.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Liga de la Justicia: Crisis en Tierras Infinitas - Parte 2 (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1209130, 'https://vimeos.net/embed-cq5aujnnefof.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Hagen - Im Tal der Nibelungen (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1208808, 'https://vimeos.net/embed-qrxs09tdbn5j.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Turno nocturno (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1208348, 'https://vimeos.net/embed-ghr5bh66kj7n.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Familia en renta (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1208284, 'https://vimeos.net/embed-x7m2xmeq1yta.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El gran golpe del este (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1208138, 'https://vimeos.net/embed-5abggn2fgmzp.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Tsunami Sharks (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1208130, 'https://vimeos.net/embed-43onj2gktq2g.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Mountain Shark (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1208002, 'https://vimeos.net/embed-sd77w4keodnw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Prodigy (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1207898, 'https://vimeos.net/embed-6w2j7gpyvz6a.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Jack en la caja maldita 3: El Ascenso (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1206617, 'https://vimeos.net/embed-utnj4xshe41h.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El mejor espectáculo Navideño de todos los tiempos (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1206558, 'https://vimeos.net/embed-23upkw3w0ph6.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Alma Wants New Playmates (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1206008, 'https://vimeos.net/embed-kr26xm7pxupn.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Ella McCay: Imperfectamente perfecta (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1205781, 'https://vimeos.net/embed-5c0nbcausmop.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Dora ¡Di Hello a la Aventura! (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1205656, 'https://vimeos.net/embed-058rn3oa0hvy.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Llamada a medianoche (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1205515, 'https://vimeos.net/embed-az16tyfej5wr.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Lo siento, bebé (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1205229, 'https://vimeos.net/embed-liyo05ienf5j.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Zoopocalipsis (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1205225, 'https://vimeos.net/embed-nodi9qu4jl4f.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Gates of Flesh (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1204912, 'https://vimeos.net/embed-29o610zrpoh2.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Enfrentando la navidad (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1204892, 'https://vimeos.net/embed-ubosak1gm758.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Retrato de un amor a ciegas (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1204881, 'https://vimeos.net/embed-wsogxw5ih716.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Edificio del Miedo (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1204812, 'https://vimeos.net/embed-gdvyycubmsid.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Familia (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1203329, 'https://vimeos.net/embed-jjbmrktycrnk.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Witcher: Sirenas de las profundidades (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1203236, 'https://vimeos.net/embed-ggxybm7hlymg.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Cascanueces (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1202863, 'https://vimeos.net/embed-gi0jtp8k765q.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Ur mörkret (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1202841, 'https://vimeos.net/embed-8fo4hmf3i5xo.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Historia de un Crimen: Mauricio Leal (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1202479, 'https://vimeos.net/embed-ckgbp15ebcrk.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Opus (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1202306, 'https://vimeos.net/embed-86ev9u406hl3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Hell House LLC: Linaje (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1201262, 'https://vimeos.net/embed-5wdvot2urng7.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Grafted (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1201197, 'https://vimeos.net/embed-jnj7fxmlimyt.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Don Q (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1201166, 'https://vimeos.net/embed-v3o8eoyryi11.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una Navidad Casi Perfecta (2021)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1200894, 'https://vimeos.net/embed-3vwp5lvrjifz.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Conflicto de Amor (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1200801, 'https://vimeos.net/embed-lbq32fwo8yfd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- F*llar Casar Matar (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1200320, 'https://vimeos.net/embed-oxxsc5dcect9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Killing Faith (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1199974, 'https://vimeos.net/embed-i4msc2drg3pd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Párvulos: Hijos del Apocalipsis (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1199869, 'https://vimeos.net/embed-ybibzk69kkux.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Ojo por Ojo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1199389, 'https://vimeos.net/embed-enfpxgwpttz8.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Red Night at Skye's (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1199193, 'https://vimeos.net/embed-o9tl6z69asjn.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Sesión fatal (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1198984, 'https://vimeos.net/embed-73dsjk3em25n.html') ON CONFLICT (tmdb_id) DO NOTHING; -- We Bury the Dead (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1198620, 'https://vimeos.net/embed-qipmyri9c0ie.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Carnage for Christmas (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1197306, 'https://vimeos.net/embed-4id4rrxl612g.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Rescate implacable (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1197239, 'https://vimeos.net/embed-4l9qsotfsjdq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Art of Telling Lies (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1197137, 'https://vimeos.net/embed-xjc6uuujzzax.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Teléfono negro 2 (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1197122, 'https://vimeos.net/embed-7ujmyz436zno.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Fils de (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1196791, 'https://vimeos.net/embed-k38m6v36xwl6.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Alma en llamas (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1196573, 'https://vimeos.net/embed-pvirkpn4wcr0.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Asiento Mortal (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1196470, 'https://vimeos.net/embed-hxlw3r126u91.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Sobreviviendo (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1196067, 'https://vimeos.net/embed-vpt7fi40qe2d.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Worldbreaker (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1195613, 'https://vimeos.net/embed-bh93c9i4zu0f.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Doin' It (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1195518, 'https://vimeos.net/embed-qoebeu2szj1y.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Maldita Trinidad (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1195506, 'https://vimeos.net/embed-t2yen2qrl5u8.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Novocaine sin dolor (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1195367, 'https://vimeos.net/embed-yen3h80z5gsk.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El Yuppie Y El Guiso (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1194963, 'https://vimeos.net/embed-jqhek5kowngu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Noise: Sonidos del más allá (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1193824, 'https://vimeos.net/embed-ahvph1jqsscl.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Rabbit Trap (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1193708, 'https://vimeos.net/embed-3566aju9yj56.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Los reyes de Queenstown (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1193620, 'https://vimeos.net/embed-e5kkum2syniu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Plan B (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1192846, 'https://vimeos.net/embed-f5jzmeqzlp2j.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Es por su bien (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1192745, 'https://vimeos.net/embed-nb0aaruwuu4q.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una Navidad escandalosa (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1192578, 'https://vimeos.net/embed-2f1lwc1iooue.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Elijo Creer: El Camino del Campeón (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1191885, 'https://vimeos.net/embed-7xwy0j4vglec.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Flashback (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1191666, 'https://vimeos.net/embed-8ivhbf1rukvp.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Le Routard (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1191611, 'https://vimeos.net/embed-qvgxvsri9orj.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Campamento con mamá (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1191610, 'https://vimeos.net/embed-3ywhppqvm1b4.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Goyo (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1191605, 'https://vimeos.net/embed-g8gkiitlq1dq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una muerte silenciosa (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1190868, 'https://vimeos.net/embed-fk3x22z0akso.html') ON CONFLICT (tmdb_id) DO NOTHING; -- V/H/S: Más allá (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (9323, 'https://vimeos.net/embed-a0z8rox66dlf.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The G (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1190150, 'https://vimeos.net/embed-qledrme4pcs5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Un buen día para morir (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1190012, 'https://vimeos.net/embed-acfexzg0tbke.html') ON CONFLICT (tmdb_id) DO NOTHING; -- South Park: Entrando al Panderverso (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1189927, 'https://vimeos.net/embed-gk3iyhloafop.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El duelo (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1189798, 'https://vimeos.net/embed-6f8in52iic3m.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Squealer (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1189198, 'https://vimeos.net/embed-s5tn946stqal.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Genie (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1187436, 'https://vimeos.net/embed-8sq0im4d19vx.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una vida honrada (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1175075, 'https://vimeos.net/embed-mcjqdhy2g9ca.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Menudas piezas (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1173559, 'https://vimeos.net/embed-4tvyj9yvy2s7.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Las puertas de infierno (2024)
