-- SQL Insert Script para video_sources
-- Generado automáticamente por Vivotv Helper

INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1426297, 'https://vimeos.net/embed-e1eyigr6twqi.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Finge Estar Muerta (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (746039, 'https://vimeos.net/embed-tip5lqrd9mzc.html') ON CONFLICT (tmdb_id) DO NOTHING; -- A Timeless Christmas (2020)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (676575, 'https://vimeos.net/embed-jlukge766tm2.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El grillo y la hormiga (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (355066, 'https://vimeos.net/embed-kur3mys3rioo.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Bad Cat (2016)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (874162, 'https://vimeos.net/embed-owjvnsivrk18.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Boyfriends of Christmas Past (2021)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1201734, 'https://vimeos.net/embed-xaua1uibo44t.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Algea: God of Pain (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1027618, 'https://vimeos.net/embed-ox49bxcr99xi.html') ON CONFLICT (tmdb_id) DO NOTHING; -- De sombra y silencio (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (179826, 'https://vimeos.net/embed-1yye772oo0hg.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Odd Thomas: Cazador de fantasmas (2013)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1175174, 'https://goodstream.one/embed-x05fkx4utrzo.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Fackham Hall (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (584634, 'https://vimeos.net/embed-h7n3unh07xq5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Soundtrack to Sixteen (2020)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (19201, 'https://vimeos.net/embed-gb1vtvo1zq3n.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La Night Del Fantasma (2013)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1290821, 'https://vimeos.net/embed-wzzqe2tyb7t3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El Guardián: Último refugio (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (642781, 'https://vimeos.net/embed-3of7etg2it5i.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El granero Parte 2 (2022)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (805473, 'https://vimeos.net/embed-46y2h9njoopv.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Breach (2022)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1631485, 'https://vimeos.net/embed-fimx9yhvhv9b.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Parque Lezama (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1214931, 'https://vimeos.net/embed-gnqfef0trvy9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Nuremberg: El juicio del siglo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1340110, 'https://vimeos.net/embed-qk5s8kjebp3g.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Matar Vengar Repetir (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1290432, 'https://vimeos.net/embed-16v8pago5fds.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Vida privada (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1310505, 'https://vimeos.net/embed-o8hyi7o9f88e.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Amor en Costa Rica (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1398911, 'https://vimeos.net/embed-xhn9zpxkp58b.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Las Chicas de Wall (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1180796, 'https://vimeos.net/embed-t1kvgcy60fhc.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Catch Me If You Claus (2023)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1028548, 'https://vimeos.net/embed-h8hk7wrdv85u.html') ON CONFLICT (tmdb_id) DO NOTHING; -- A Fabled Holiday (2022)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (790894, 'https://vimeos.net/embed-3f7abafqf273.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Paradise Cove (2021)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (820696, 'https://vimeos.net/embed-xhwzjz4gx6h3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Amor Fuera De Tiempo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (59387, 'https://vimeos.net/embed-7iubbgskwuzp.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Las Chicas Superpoderosas: La película (2002)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (680493, 'https://vimeos.net/embed-2hyj4sw0xcor.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Terror en Silent Hill: Regreso al infierno (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (388, 'https://vimeos.net/embed-xsowbcd6l7lf.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El Plan Perfecto (2006)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (246569, 'https://vimeos.net/embed-3mad2lf9eh1j.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Jinxed: Cuestión de Suerte (2013)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1613798, 'https://vimeos.net/embed-edo65cxw6aj9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Venganza (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1305715, 'https://vimeos.net/embed-wbsmaefe1st1.html') ON CONFLICT (tmdb_id) DO NOTHING; -- 过家家 (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1612063, 'https://vimeos.net/embed-p21de333e6vu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Twenty One Pilots: More Than We Ever Imagined (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (8066, 'https://vimeos.net/embed-vqm42cwpd3po.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El umbral (2005)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1575534, 'https://vimeos.net/embed-4vk1ic1yupl1.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Observance (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242937, 'https://vimeos.net/embed-4w41obx2zm2n.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Dreadful (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1159831, 'https://vimeos.net/embed-nt0d365ljgls.html') ON CONFLICT (tmdb_id) DO NOTHING; -- ¡La novia! (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1107166, 'https://vimeos.net/embed-zjvvwgcblrim.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Psycho Killer (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1363381, 'https://vimeos.net/embed-7b0eesrrcka0.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Petaka Gunung Gede (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1506323, 'https://vimeos.net/embed-ccjdhb2blgww.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Minnie’s Midnight Massacre (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1125701, 'https://vimeos.net/embed-wb6th9djg844.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Midwinter Break (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1586941, 'https://vimeos.net/embed-o8ys4dqqt2p2.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Herman (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (467905, 'https://vimeos.net/embed-8lrj7v4ityix.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Jugada maestra (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1582339, 'https://vimeos.net/embed-g1av6i9q2ewv.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Haunters of the Silence (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1088434, 'https://vimeos.net/embed-vxskgknibeqw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Hellfire (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1390382, 'https://vimeos.net/embed-66w4of4lun7s.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Couture (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1355496, 'https://vimeos.net/embed-tkwsgo2xy5oq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- By Design (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1561687, 'https://vimeos.net/embed-u2grzqtc9mej.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Un destino en Corea (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1251683, 'https://vimeos.net/embed-3q5of6liuvce.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Ba (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1621612, 'https://vimeos.net/embed-qm2c19wn5cs9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Tears to a Glass Eye (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1618945, 'https://vimeos.net/embed-ist3euogtfle.html') ON CONFLICT (tmdb_id) DO NOTHING; -- ¡Uf! ¿Solo amigos? (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1618086, 'https://vimeos.net/embed-bdgtwq945aw9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Knock Knock Man (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1612424, 'https://vimeos.net/embed-kls9bp0yg1ag.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Repay It in Blood (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1610413, 'https://vimeos.net/embed-g7hk87zoiahr.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una última aventura: Detrás de cámaras de Stranger Things 5 (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1610042, 'https://vimeos.net/embed-iikuprszf2xr.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Mama's Little Murderer (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1608982, 'https://vimeos.net/embed-uqru7gfswitn.html') ON CONFLICT (tmdb_id) DO NOTHING; -- De las cenizas: Bajo tierra (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1603194, 'https://vimeos.net/embed-ugqp1etaa8bd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Enter Sanctum (None)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1602705, 'https://vimeos.net/embed-pn1u1x5yvhfu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una carta a mi juventud (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1601243, 'https://vimeos.net/embed-22rgbjfcgosd.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Oscar Shaw (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1600028, 'https://vimeos.net/embed-ujjph6iacbsm.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La celda de los milagros (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1594286, 'https://vimeos.net/embed-bctxby7n02uk.html') ON CONFLICT (tmdb_id) DO NOTHING; -- You're All Doomed (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1591822, 'https://vimeos.net/embed-gtimiknub5tj.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Pandora: Fire and Ice (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1589891, 'https://vimeos.net/embed-0yj58dbp5kr8.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La hora de los valientes (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1589530, 'https://vimeos.net/embed-swrl10mxl91n.html') ON CONFLICT (tmdb_id) DO NOTHING; -- A Town Called Purgatory (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1586841, 'https://vimeos.net/embed-sj8tiqndeumt.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El paseo 8 (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1584628, 'https://vimeos.net/embed-w1gj8yijn2jc.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Borrón y Vida Nueva (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1495638, 'https://vimeos.net/embed-79wpwzg7xrsq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Caretaker (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1584468, 'https://vimeos.net/embed-s8co3hiidczk.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Down River (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1581486, 'https://vimeos.net/embed-ojhp860yys9o.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Dreamer Cinderella (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1577007, 'https://vimeos.net/embed-bccqu0zyxpx7.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Amorosa (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1576997, 'https://vimeos.net/embed-wh852ci18dlb.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Nadie sabe quién soy yo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1576166, 'https://vimeos.net/embed-7zmhgziq8zws.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Ojalá me lo hubieras dicho (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1575535, 'https://vimeos.net/embed-54w9vgf7bb7o.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Tormento (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1575337, 'https://vimeos.net/embed-v8vsx7w3g0bc.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La princesa Kaguya del cosmos (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1574181, 'https://vimeos.net/embed-zrzr8tcv6gf5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Inthralled (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1571470, 'https://vimeos.net/embed-v6gi9jxwlh5k.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Las Ratas: Una historia de The Witcher (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1570282, 'https://vimeos.net/embed-duqdcx9fndgi.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Ahí estoy yo (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1566269, 'https://vimeos.net/embed-iohebpkjg37z.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La primera nevada en Fraggle Rock (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1566001, 'https://vimeos.net/embed-91hv31bica3a.html') ON CONFLICT (tmdb_id) DO NOTHING; -- VHS Summer Camp (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1565779, 'https://vimeos.net/embed-kui8vy4ab8kt.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Luderdale (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1565344, 'https://vimeos.net/embed-kxdbdsf2usgw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Parking (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1563506, 'https://vimeos.net/embed-7phb5kakaw42.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Hogar siniestro (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1561969, 'https://vimeos.net/embed-1bomg53826d9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Baramulla (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1561955, 'https://vimeos.net/embed-u36uv5a6w5jp.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Stephen (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1560664, 'https://vimeos.net/embed-4ebo9kbs48cu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Roughneck (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1556834, 'https://vimeos.net/embed-4pahvxfpu00m.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Lost Horizon (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1555571, 'https://vimeos.net/embed-8uyo0qs0nbms.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Signing Tony Raymond (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1552525, 'https://vimeos.net/embed-6obv9gcke10g.html') ON CONFLICT (tmdb_id) DO NOTHING; -- The Raven (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1550797, 'https://vimeos.net/embed-85ysydkiinju.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Patrulla de aterrizaje: Operación bola de nieve (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1550223, 'https://vimeos.net/embed-d269wmafeier.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El tiempo que nos queda (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1549608, 'https://vimeos.net/embed-kcvy399fctl5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Blindly in Love (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1549292, 'https://vimeos.net/embed-kxp0rwzrivfs.html') ON CONFLICT (tmdb_id) DO NOTHING; -- LEGO Frozen: Operation Puffins (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1548113, 'https://vimeos.net/embed-ee3taj6t7twz.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Los Muppets: Un show especial (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1546933, 'https://vimeos.net/embed-964qodko8dxu.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Rockstar: DUKI desde el fin del mundo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1546050, 'https://vimeos.net/embed-6cizz3m1vi70.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Lone Samurai (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1545274, 'https://vimeos.net/embed-q0r02ppktrpx.html') ON CONFLICT (tmdb_id) DO NOTHING; -- LO QUE SE OCULTA EN LAS SOMBRAS (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1543831, 'https://vimeos.net/embed-8iei5dkoe566.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Speed Train (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1535290, 'https://vimeos.net/embed-m2zlmp8tds6g.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La huésped (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1529517, 'https://vimeos.net/embed-jgcmh4l0c52i.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Reinas de la Noche (2025)
