-- SQL Insert Script para video_sources
-- Generado automáticamente por Vivotv Helper

INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1252382, 'https://vimeos.net/embed-u5p3pn9ktqu1.html') ON CONFLICT (tmdb_id) DO NOTHING; -- En busca de la felicidad (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1252377, 'https://vimeos.net/embed-mrifun5zbdr5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La dolce casa (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1252309, 'https://vimeos.net/embed-jos3jun8ifim.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Pídeme lo que quieras (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1252037, 'https://vimeos.net/embed-tt656uew159s.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Tiger: Tanque de guerra (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1251717, 'https://vimeos.net/embed-0q0jak53txsm.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Regalo maldito (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1249532, 'https://vimeos.net/embed-ufsy1ivk4nbi.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Rippy (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1249289, 'https://vimeos.net/embed-x2dwm12825bq.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Alarum: Código Letal (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1249213, 'https://vimeos.net/embed-w10upk2hwr17.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Drop: Amenaza anónima (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1248753, 'https://vimeos.net/embed-yvtldhzha8w5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Alerta Amber (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1248711, 'https://vimeos.net/embed-v3uhoyhokqvw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- So Fades the Light (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1248226, 'https://vimeos.net/embed-erbu1wnxq49z.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Un día fuera de control (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1247019, 'https://vimeos.net/embed-wwllczyir02s.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Thi Yot 2 - Susurros Mortales 2 (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1246310, 'https://vimeos.net/embed-0nzj3bpidx92.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Una boda en las bahamas con madea (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1246049, 'https://vimeos.net/embed-162wzuryvd2c.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Drácula (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1245993, 'https://vimeos.net/embed-kb2ttpk87rva.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Atrapado robando (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1245934, 'https://vimeos.net/embed-q04zrmxf8exg.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Séance Games: Metaxu (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1245708, 'https://vimeos.net/embed-xe321cg0q9t3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Crescent City (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1245165, 'https://vimeos.net/embed-p16g7qab87x5.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Viaje de fin de curso: Mallorca (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1244975, 'https://vimeos.net/embed-nrr9e1794ypn.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Los huérfanos (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1244953, 'https://vimeos.net/embed-cozbbsxc76c9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Trust (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1244944, 'https://vimeos.net/embed-ctumgfmqirz9.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La mujer de las sombras (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1244492, 'https://vimeos.net/embed-qg4wxh53j7lw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- LOOK BACK: Continúa Dibujando (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1244039, 'https://vimeos.net/embed-r72nqxdvmaem.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Asesinos Sadicos 2 Hermanos Hambrientos (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1243895, 'https://vimeos.net/embed-34i0mcv4m60j.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Canta y no llores (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1243460, 'https://vimeos.net/embed-npwekogzfd6j.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El tour universitario con Joe (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (971968, 'https://vimeos.net/embed-35ejzk76ijxl.html') ON CONFLICT (tmdb_id) DO NOTHING; -- María (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1243341, 'https://vimeos.net/embed-0qlsq4muguuc.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Z-O-M-B-I-E-S 4: El origen de los vampiros (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1243006, 'https://vimeos.net/embed-gi27l6om5jmf.html') ON CONFLICT (tmdb_id) DO NOTHING; -- H Is for Hawk (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242898, 'https://vimeos.net/embed-gifb0mvp14aw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Depredador: Tierras salvajes (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242705, 'https://vimeos.net/embed-495snhoasgi4.html') ON CONFLICT (tmdb_id) DO NOTHING; -- One More Shot (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242669, 'https://vimeos.net/embed-2i5vmcebs2ln.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Mr. K (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242501, 'https://vimeos.net/embed-g4vqyhnyw6af.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Icefall (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242434, 'https://vimeos.net/embed-yj28nqqoistv.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Del cielo al infierno (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242426, 'https://vimeos.net/embed-2r8vapc469hs.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Regarde (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242419, 'https://vimeos.net/embed-fc4eufatv3cp.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Un Buen Ladrón (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242404, 'https://vimeos.net/embed-cv2kv13dygwx.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Steve (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242384, 'https://vimeos.net/embed-p8bb1bvkzybl.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La red antisocial: De los memes al caos (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1242011, 'https://vimeos.net/embed-bctb56wi6xca.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Together: Juntos hasta la muerte (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1241983, 'https://vimeos.net/embed-i14yhbo6r95l.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Sueños de trenes (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1241982, 'https://vimeos.net/embed-b7o6j67cn5pr.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Moana 2 (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1241934, 'https://vimeos.net/embed-gjcr5l0zjxz1.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Policías de la mafia (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1241921, 'https://vimeos.net/embed-x6rs1ymcd9o4.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El gran viaje de tu vida (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1241726, 'https://vimeos.net/embed-txkc3kzdgazw.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Candlewood (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1241634, 'https://vimeos.net/embed-4bkyailjsrb8.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Saiyaara (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1241231, 'https://vimeos.net/embed-wzrsmdk0gae3.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Rehenes en la noche (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1239655, 'https://vimeos.net/embed-2xaeh00lp8pm.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Friendship (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1239251, 'https://vimeos.net/embed-0g4ctifm8d0n.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Megamente contra el sindicato de la perdición (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1239193, 'https://vimeos.net/embed-tcuw1d1b0rqb.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Acto encubierto (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1239146, 'https://vimeos.net/embed-iww59cbo9c1h.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El Pájaro Loco se va de campamento (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1239115, 'https://vimeos.net/embed-hdcjlyz7908p.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Warlord (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1238379, 'https://vimeos.net/embed-un9joi8xi5en.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Lo Mejor Que Puedas (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1238307, 'https://vimeos.net/embed-riqu1fzaguvm.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Masameer Junior (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1238252, 'https://vimeos.net/embed-n9juk4kpfkw8.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Kindred (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1238188, 'https://vimeos.net/embed-ae6r0l44zkyi.html') ON CONFLICT (tmdb_id) DO NOTHING; -- El cautivo (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1238127, 'https://vimeos.net/embed-gggrvi84wvf6.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Los desfiles (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1237266, 'https://vimeos.net/embed-6kth48u58zc0.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Runt (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1237082, 'https://vimeos.net/embed-z31m3zho0x3v.html') ON CONFLICT (tmdb_id) DO NOTHING; -- 31 Minutos: Calurosa Navidad (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1236471, 'https://vimeos.net/embed-g1hsocn16czo.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Cumpleanos sangriento (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1236470, 'https://vimeos.net/embed-427ti7qei95w.html') ON CONFLICT (tmdb_id) DO NOTHING; -- A través del fuego (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1236419, 'https://vimeos.net/embed-f978f307d8vn.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Pharrell Williams: Pieza por pieza (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1236416, 'https://vimeos.net/embed-na1afjpztl21.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Wolves Against the World (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1236197, 'https://vimeos.net/embed-ai6xd9mi1e32.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Juegos de Seducción (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1236153, 'https://vimeos.net/embed-7bplwv3deni4.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Sin piedad (2026)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1235913, 'https://vimeos.net/embed-drkh2a0hd77m.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Yo no soy esa (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1235746, 'https://vimeos.net/embed-jt0wegwrhje8.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Muerte en invierno (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1235610, 'https://vimeos.net/embed-1msiryzhm9zk.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Mercato (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1235499, 'https://vimeos.net/embed-caib3gu0u6rl.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La Última Gran Actuación (2024)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1235277, 'https://vimeos.net/embed-t4bol3ghsvm4.html') ON CONFLICT (tmdb_id) DO NOTHING; -- La pire mère au monde (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1235192, 'https://goodstream.one/embed-dgxuf6amjon7.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Wormtown (2025)
INSERT INTO video_sources (tmdb_id, stream_url) VALUES (1234821, 'https://vimeos.net/embed-r5xuubxljw1k.html') ON CONFLICT (tmdb_id) DO NOTHING; -- Jurassic World: Renace (2025)
